language: ruby
cache: bundler

rvm:
  - 2.3.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - david.alphen@gmail.com
      - mrdougwright@gmail.com
    on_failure: change
    on_success: never
